services:
  mysql:
    image: mysql
    container_name: database
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "3002:8080"
    depends_on:
      - mysql
  frontend:
    build: front/
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    environment:
      mode: production
      VUE_APP_BACKEND: backend
    depends_on:
      - backend
  backend:
    build: backend/
    container_name: backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      DB_HOST: mysql
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      APP_PORT: 3001
    depends_on:
      - mysql
volumes:
  db:
