version: '3'
services:
  mysql:
    image: mysql
    restart: always
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - mysql
  frontend:
    image: node:14.16.1-alpine
    volumes:
      - "./front:/app"
    working_dir: /app
    ports:
      - ${FRONTEND_PORT}:8080
    environment:
      mode: development
    command: sh -c "cd /app; npm install; npm run serve"
    depends_on:
      - backend
  backend:
    image: node:14.16.1-alpine
    working_dir: /usr/src/app
    volumes:
      - "./back:/usr/src/app"
    command: sh -c "cd /server; npm i; npm i nodemon; npm run dev"
    restart: always
    ports:
      - ${BACKEND_PORT}:3001
    environment:
      DB_HOST: mysql
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - mysql
volumes:
  db:
