version: '3'
services:
  mysql:
    image: mysql
    restart: always
    container_name: database
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - mysql
  frontend:
    build: front/
    restart: always
    container_name: frontend
    ports:
      - ${FRONTEND_PORT}:80
    environment:
      mode: production
      VUE_APP_BASE_URL: backend
    depends_on:
      - backend
  backend:
    build: backend/
    restart: always
    container_name: backend
    ports:
      - ${BACKEND_PORT}:3001
    environment:
      DB_HOST: mysql
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    depends_on:
      - mysql
volumes:
  db:
