version: '3'
services:
  db:
    image: mysql
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${POSTGRES_PASS}
  backend:
    build: greenapp-back/
    restart: always
    ports:
      - ${BACKEND_PORT}:3001
    environment:
      PG_PASS: ${POSTGRES_PASS}
    depends_on:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - db
  frontend:
    build: greenapp-front/
    restart: always
    ports:
      - ${FRONTEND_PORT}:80
    environment:
      mode: development
    depends_on:
      - backend
