name: GitHub Actions Demo
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.16.1 ]
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-verson:  ${{ matrix.node-version }}
      - name: Install deps
        run: npm i
      - name: build project
        run: cd front && npm run build
